import { test, expect } from '@playwright/test'
test('keyboard history, group movement, ungroup, and minimap', async ({
  page,
}) => {
  await page.goto('/canvas/new')
  await page.getByRole('button', { name: 'Add node', exact: true }).waitFor()
  await page.keyboard.press('n')
  await expect(page.locator('.react-flow__node-block')).toHaveCount(1)
  await page.keyboard.press('Meta+d')
  await expect(page.locator('.react-flow__node-block')).toHaveCount(2)
  await page.keyboard.press('Meta+z')
  await expect(page.locator('.react-flow__node-block')).toHaveCount(1)
  await page.keyboard.press('Meta+Shift+z')
  await expect(page.locator('.react-flow__node-block')).toHaveCount(2)
  await page.keyboard.press('Meta+a')
  await page
    .getByRole('button', { name: 'Group selected', exact: true })
    .click()
  await expect(page.locator('.kind-section')).toHaveCount(1)
  const child = page
    .locator('.react-flow__node-block')
    .filter({ has: page.locator('.kind-standard') })
    .first()
  const before = await child.boundingBox()
  const title = page.locator('.kind-section .block-title')
  const box = await title.boundingBox()
  if (!box || !before) throw Error('Missing group')
  await title.hover({ position: { x: 5, y: 25 } })
  await page.mouse.down()
  await page.mouse.move(box.x + 75, box.y + 80, { steps: 10 })
  await page.mouse.up()
  expect((await child.boundingBox())!.x).toBeGreaterThan(before.x + 40)
  await page
    .getByRole('button', { name: 'Ungroup selected', exact: true })
    .click()
  await expect(page.locator('.kind-section')).toHaveCount(0)
  await page.getByRole('button', { name: 'Undo', exact: true }).click()
  await expect(page.locator('.kind-section')).toHaveCount(1)
  await page
    .getByRole('button', { name: 'Toggle minimap', exact: true })
    .click()
  await expect(page.locator('.react-flow__minimap')).toBeVisible()
})
test('slash menu inserts headings', async ({ page }) => {
  await page.goto('/canvas/new')
  await page.getByRole('button', { name: 'Add node', exact: true }).waitFor()
  await page.keyboard.press('n')
  await page.getByRole('button', { name: 'Edit node', exact: true }).click()
  const editor = page.getByRole('textbox', { name: 'Node content' })
  await editor.fill('/')
  await page.getByRole('menuitem', { name: 'Heading', exact: true }).click()
  await editor.pressSequentially('A clear thought')
  await expect(editor.locator('h2')).toHaveText('A clear thought')
})
