import { useEffect, useState } from 'react'
import { EditorContent, useEditor } from '@tiptap/react'
import StarterKit from '@tiptap/starter-kit'
import TextAlign from '@tiptap/extension-text-align'
import { TextStyle, FontSize } from '@tiptap/extension-text-style'
import { AlignCenter, AlignLeft, AlignRight, Bold, Code, Italic, Link as LinkIcon, List, ListOrdered, Strikethrough, Underline } from 'lucide-react'
export default function RichEditor({content,onChange,active}:{content:string;onChange:(html:string)=>void;active:boolean}) {
 const [slash,setSlash]=useState(false)
 const editor=useEditor({extensions:[StarterKit.configure({codeBlock:false,link:{openOnClick:false}}),TextAlign.configure({types:['heading','paragraph']}),TextStyle,FontSize],content,editable:active,onUpdate:({editor})=>{onChange(editor.getHTML());setSlash(editor.state.selection.$from.parent.textContent.endsWith("/"))},editorProps:{attributes:{'aria-label':'Node content',role:'textbox','aria-multiline':'true',class:'node-editor'}}})
 useEffect(()=>{editor?.setEditable(active)},[editor,active])
 useEffect(()=>{if(editor&&editor.getHTML()!==content)editor.commands.setContent(content,{emitUpdate:false})},[editor,content])
 if(!editor)return null
 const format=(name:string,icon:React.ReactNode,action:()=>void)=><button key={name} title={name} aria-label={name} onMouseDown={e=>e.preventDefault()} onClick={action}>{icon}</button>
 return <div className="rich-editor nodrag nowheel" onKeyDown={e=>e.stopPropagation()}>{active&&<div className="format-toolbar" role="toolbar" aria-label="Text formatting"><select aria-label="Text style" defaultValue="paragraph" onChange={e=>{const c=editor.chain().focus();if(e.target.value==='paragraph')c.setParagraph().run();else c.toggleHeading({level:Number(e.target.value) as 1|2|3}).run()}}><option value="paragraph">Text</option><option value="1">Heading 1</option><option value="2">Heading 2</option><option value="3">Heading 3</option></select><select aria-label="Font size" defaultValue="14px" onChange={e=>editor.chain().focus().setFontSize(e.target.value).run()}>{[12,14,16,20,24,32].map(n=><option key={n} value={`${n}px`}>{n}</option>)}</select>{format('Bold',<Bold size={14}/>,()=>{editor.chain().focus().toggleBold().run()})}{format('Italic',<Italic size={14}/>,()=>{editor.chain().focus().toggleItalic().run()})}{format('Underline',<Underline size={14}/>,()=>{editor.chain().focus().toggleUnderline().run()})}{format('Strikethrough',<Strikethrough size={14}/>,()=>{editor.chain().focus().toggleStrike().run()})}{format('Inline code',<Code size={14}/>,()=>{editor.chain().focus().toggleCode().run()})}{format('Bullet list',<List size={14}/>,()=>{editor.chain().focus().toggleBulletList().run()})}{format('Numbered list',<ListOrdered size={14}/>,()=>{editor.chain().focus().toggleOrderedList().run()})}{format('Align left',<AlignLeft size={14}/>,()=>{editor.chain().focus().setTextAlign('left').run()})}{format('Align center',<AlignCenter size={14}/>,()=>{editor.chain().focus().setTextAlign('center').run()})}{format('Align right',<AlignRight size={14}/>,()=>{editor.chain().focus().setTextAlign('right').run()})}{format('Link',<LinkIcon size={14}/>,()=>{const href=window.prompt('Link URL (https://…); leave empty to remove',editor.getAttributes('link').href||'https://');if(href===null)return;if(!href)editor.chain().focus().unsetLink().run();else if(/^https?:\/\//i.test(href))editor.chain().focus().extendMarkRange('link').setLink({href}).run()})}</div>}{active&&slash&&<div className="slash-menu" role="menu" aria-label="Insert content">{['Heading','Bullet list','Numbered list','Inline code'].map(label=><button key={label} role="menuitem" onMouseDown={e=>e.preventDefault()} onClick={()=>{const pos=editor.state.selection.from;const c=editor.chain().focus().deleteRange({from:pos-1,to:pos});if(label==='Heading')c.toggleHeading({level:2}).run();else if(label==='Bullet list')c.toggleBulletList().run();else if(label==='Numbered list')c.toggleOrderedList().run();else c.toggleCode().run();setSlash(false)}}>{label}</button>)}</div>}<EditorContent editor={editor}/></div>
}
